### ISSUE TITLE
7.2 please

### ISSUE THREAD

**Issue by fommil** [jmcardon/IOPort#6]
I'd love to use this in my book, but it needs to work for scalaz 7.2 (and have artefacts on maven central)... can you please use the package `scalaz.backport.effect` ?

**Comment by emilypi** [comment]
@jmcardon This weekend - lets cut a release to `scalaz`

**Comment by fommil** [comment]
also, turn all the optimisations to the max on scala 2.12 and use that monadic for magic... let's see if it makes a difference in your benchmarks!
